<div class="admin__styles-table">
    <table class="table table-condensed">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
        <?php foreach ($authors as $author) : ?>
        <tr>
            <td><?=$author->getId()?></td>
            <td><?=$author->getName()?></td>
            <td>
                <a href="/admin/authors/edit/<?=$author->setAuthorForView($author->getName())?>.html" class="btn btn-default btn-success btn-sm" aria-label="Left Align">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="#" class="btn btn-default btn-danger btn-sm" aria-label="Left Align">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
    </table>
</div>