<div class="admin__styles-table">
    <table class="table table-condensed">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
        <?php foreach ($authors as $author) : ?>
        <tr>
            <td><?=$author->getId()?></td>
            <td><a href="/admin/authors/show/<?=$author->setAuthorForView($author->getName());$author->getId()?>.html"><?=$author->getName()?></a></td>
            <td>
                <a href="/admin/authors/edit/<?=$author->setAuthorForView($author->getName())?>.html" class="btn btn-default btn-success btn-sm" aria-label="Left Align">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="/admin/authors/delete/<?=$author->setAuthorForView($author->getName());$author->getId()?>.html" class="btn btn-default btn-danger btn-sm" aria-label="Left Align">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
    </table>

    <form method="post" action="/admin/authors/add">
        <fieldset >
            <legend>Add New Author</legend>
            <div class="form-group">
                <label for="author_name">Author Name:</lable>    
                <input class="form-control" type="text" id="author_name" name="author_name" placeholder="Author Name">
            </div>
            <div class="form-group">    
                <label for="descr">Description:</label>
                <textarea id="descr" name="descr" class="form-control" placeholder="Author Description"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </fieldset>
    </form>
</div>