<div class="admin__books-table">
<table class="table table-condensed">
<thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Price</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>
    <?php foreach ($books as $book) : ?>
    <tr>
        <td><?=$book->getId()?></td>
        <td><?=$book->getTitle()?></td>
        <td><?=$book->getPrice()?></td>
        <td>
            <a href="#" class="btn btn-default btn-success btn-sm" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>
            <a href="#" class="btn btn-default btn-danger btn-sm" aria-label="Left Align">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </a>
        </td>
    </tr>
    <?php endforeach ?>
</tbody>
</table>
</div>
<nav aria-label="Page navigation">
  <ul class="pagination">

    <?php foreach($pagination->buttons as $button) : ?>
        <li>
            <?php if ($button->isActive) : ?>
                <!--
                <a href="/admin/index.php?route=book/index&amp;page=<?=$button->page?>"><?=$button->text?></a>
                -->
                <a href="/admin/books_management/book-list-<?= $button->page?>">
                <?=$button->text?> </a>
            <?php else : ?>
                <span aria-hidden="true"><?=$button->text?></span>
            <?php endif ?>
        </li>
    <?php endforeach ?>
  </ul>
</nav>

<!-- 


-->