<h1>Feedback</h1>

<form action="" method='post'>
    <input class="form-control" type="text" name="author" placeholder="Author Name:" value="<?=$form->author ?>"/><br>
    <input class="form-control" type="text" name="email" placeholder="Email:" value="<?=$form->email?>" /><br>
    <textarea class="form-control" name="message" placeholder="Your message:" value="<?=$form->message?>"></textarea><br>
    <button class="btn btn-primary">Go</button>
</form>