<div id="admin__styles-table">
    <table class="table table-condensed">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
        <?php foreach ($styles as $style) : ?>
        <tr>
            <td><?=$style->getId()?></td>
            <td><?=$style->getTitle()?></td>
            <td>
                <a href="/admin/styles/edit/<?=$style->setStyleForView($style->getTitle())?>.html" class="btn btn-default btn-success btn-sm" aria-label="Left Align">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="#" class="btn btn-default btn-danger btn-sm" aria-label="Left Align">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
    </table>
</div>