<h1>Books</h1>
<nav aria-label="Page navigation">
  <ul class="pagination">

  	<?php foreach($pagination->buttons as $button) : ?>
  		<li>
  			<?php if ($button->isActive) : ?>
  				<a href="/book_list-<?=$button->page?>"><?=$button->text?></a>
  			<?php else : ?>
  				<span aria-hidden="true"><?=$button->text?></span>
  			<?php endif ?>
  		</li>
  	<?php endforeach ?>
  </ul>
</nav>
<div class="row">

  <?php foreach ($books as $book) : ?>
	  <div class="col-sm-6 col-md-4">
	    <div class="thumbnail book-item">
	      <img src="/images/cat.jpg" width="300" height="300" alt="...">
	      <div class="caption">
	        <h3><?= $book->getTitle() ?></h3>
	        <p><?= $book->getDescription() ?></p>
	        <p>
	        	<a href="/book-<?=$book->getId()?>.html" class="btn btn-primary" role="button">Details</a>
	        	<a href="#" class="btn btn-default" role="button">Add to Cart</a>
	        </p>
	      </div>
	    </div>
	  </div>
  <?php endforeach ?>

</div>